Default: &defaults
  database: fabulor.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: fabulor_test.sqlite3
  <<: *defaults

Staging:
  database: fabulor_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: fabulor_production.sqlite3
  poolsize: 100
  <<: *defaults
